services:
  init-data:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - broker
      - database
      - web
    command: >
      sh -c "pip install confluent-kafka faker && 
             python ./insert-data.py"

  database:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=ttj
      - CLICKHOUSE_PASSWORD=ttj123
      - CLICKHOUSE_DB=kafka_clickhouse
      - CLICKHOUSE_HTTP_ALLOW_CORS=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 3s
      timeout: 3s
      retries: 10

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  web:
    build: .
    container_name: react-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures Hot Module Replacement (HMR) works in Docker
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_started
    command: >
      sh -c "npm run migrate; npm run dev"

  api-server:
    build: .
    container_name: node-api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - KAFKA_BROKER=broker:9092
      - CLICKHOUSE_HOST=http://database:8123
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_started
    command: npm run start:server
